### ISSUE TITLE
CoC - Language Clarification - Promote a Product

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/code-of-conduct#5]
The following change to the Code of Conduct is being proposed to remove ambiguity concerning a particular phrase but keep the values of FreeCodeCamp.

The phrase in question is "promoting a product" and its related advertising employment opportunites

Current Wording:

- Spamming includes posting off-topic messages to disrupt discussions, promoting a product, soliciting donations, advertising a job / internship / gig, or flooding discussions with files or text.

Proposed Solution:

remove 'the 'promoting a product' and 'advert a job/internship/gig' out of 'Spamming' category into its own category so it is clearly visible, removes ambiguity and remains consistent.

- Promoting/Advertising includes promoting a product, service or resource for the purposes of gaining social visibility and/or a direct financial gain. Advertising employment, internship or freelance opportunities.,

- Spamming includes posting off-topic messages to disrupt discussions, soliciting donations, flooding discussions with files, text or images.

**Comment by QuincyLarson** [comment]
Hi @mstellaluna thanks for broaching this topic. Currently we have 3 bullets, and I think adding any more would further decrease people's likelihood of reading the Code of Conduct at all.

I took your recommended verbiage and did my best to work it into a two-sentence definition of spamming:

> Spamming includes trying to disrupt discussions by posting off-topic messages, files, or text. It also includes promoting a product, service, resource, or job for the purpose of exposure or financial gain.

**Comment by mstellaluna** [comment]
@QuincyLarson you left out 'soliciting donations' :) 
So 
"Spamming includes trying to disrupt discussions by posting off-topic messages, files, or text. It also includes soliciting donations, promoting a product, service, resource, or job for the purpose of exposure or financial gain."

**Comment by ArielLeslie** [comment]
Where/how do we draw the line of "for the purpose of exposure"? If a member of the community creates a video/article/twitch channel/etc that is a legitimate resource, do we remove it because they can also benefit from it in either a material or abstract way?

**Comment by mstellaluna** [comment]
@ArielLeslie We share resources all the time in either forum or chat, I don't think it should stop anyone from doing what we always do. 

I had asked for a clarification based on comments/feedback from the chat members about self-made content being shared if someone needs extra help on a particular topic. 

It was more to clarify situations (I don't know if you get these in the forum) where people come in out of the blue, post their link and ask for subs, stars and/or gain referrals.  

When I mention its against the CoC to those situations I always get the comment back "it's not in the Code of Conduct, what's the problem".

**Comment by ArielLeslie** [comment]
Maybe we just haven't had a problem with having to justify "promoting a product" applying to someone's publication, etc.

My concern is just that we don't ban useful content just because the creator does benefit from sharing it.  That may just mean a corresponding clarification in moderator guidelines.

**Comment by QuincyLarson** [comment]
@mstellaluna Good catch on soliciting donations.

@ArielLeslie Perhaps we could reword the "promoting a product" to this:

"Spamming includes trying to disrupt discussions by posting off-topic messages, files, or text. It also includes soliciting donations, promoting a product, service, resource, or job for the **primary** purpose of exposure or financial gain."

If the primary purpose of sharing a link to a job posting or blog post is to contribute to conversation, no problems there. But if it's primarily just them plugging something when it otherwise doesn't add to the discussion, then there's a problem.

Again, there is going to be gray area either way. The moment we clearly define "exposure" people will start to game it. This will always have to be subjectively determined by mods.

What do you all think of this copy? Anything else we should do to it before @mstellaluna opens the PR to update the CoC?

**Comment by QuincyLarson** [comment]
@mstellaluna OK - @ArielLeslie seems to think this works, and no one else seems to have an opinion on it (she linked to it in the forum moderator section) so I think you can go ahead and open a PR :)

**Comment by RandellDawson** [comment]
Sorry for the late response.

@QuincyLarson - Do you have an example of a post sharing a link about a job posting where it would be contributing to a conversation?  I see many posts about job postings and I have always flagged them as SPAM.

> If the primary purpose of sharing a link to a job posting or blog post is to contribute to conversation, no problems there. But if it's primarily just them plugging something when it otherwise doesn't add to the discussion, then there's a problem.

**Comment by QuincyLarson** [comment]
@randelldawson I don't have a good example of this. I recommend we blanket-ban linking to job posts (as we have in the above copy) and allow for moderators to make exceptions in cases where it's clearly not spamming. As always, the ultimate decision will come down to the individual moderator reviewing the post.

**Comment by raisedadead** [comment]
> ### This page is now archived and managed in Ghost
